# Lima config for Podman on Apple Silicon
arch: "aarch64"
images:
  - location: "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-arm64.img"
    arch: "aarch64"
    digest: ""

mounts:
  - location: "~"
    writable: true

containerd:
  system: false
  user: false

provision:
  - mode: system
    script: |
      #!/bin/bash
      apt-get update
      apt-get install -y software-properties-common
      . /etc/os-release
      echo "Installing Podman..."
      source /etc/os-release
      . /etc/os-release
      . /etc/os-release
      . /etc/os-release
      echo "deb http://deb.debian.org/debian bullseye-backports main" >> /etc/apt/sources.list
      apt-get update
      apt-get -t bullseye-backports install -y podman
      echo "alias podman='podman --remote'" >> /etc/profile
      echo "export DOCKER_HOST=unix:///run/user/1000/podman/podman.sock" >> /etc/profile

ssh:
  localPort: 60022

portForwards:
  - guestPort: 8080
    hostPort: 8080
  - guestPort: 5555
    hostPort: 5555