arch: "aarch64"

images:
  - location: "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-arm64.img"
    arch: "aarch64"

mounts:
  - location: "~"
    writable: true

containerd:
  system: false
  user: false

provision:
  - mode: system
    script: |
      #!/bin/bash
      set -eux

      apt-get update
      apt-get install -y software-properties-common curl uidmap gnupg lsb-release python3-pip

      # Add official Podman PPA for Ubuntu 20.04 (Focal)
      source /etc/os-release
      echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
      curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | apt-key add -

      apt-get update
      apt-get install -y podman

      # Ensure Podman is accessible to subprocesses like podman-compose
      ln -sf $(command -v podman) /usr/local/bin/podman

      # Global shell environment
      echo 'export PATH="/usr/local/bin:/usr/bin:$PATH"' >> /etc/profile
      echo 'export DOCKER_HOST=unix:///run/user/1000/podman/podman.sock' >> /etc/profile
      echo 'alias podman="podman --remote"' >> /etc/profile

  - mode: user
    script: |
      mkdir -p ~/.local/bin

      # Create wrapper shim for podman in ~/.local/bin
      cat <<'EOF' > ~/.local/bin/podman
      #!/bin/bash
      exec /usr/local/bin/podman "$@"
      EOF

      chmod +x ~/.local/bin/podman

      echo 'export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH"' >> ~/.bashrc
      echo 'export DOCKER_HOST=unix:///run/user/1000/podman/podman.sock' >> ~/.bashrc
      echo 'alias podman="podman --remote"' >> ~/.bashrc
      source ~/.bashrc

      pip3 install --user podman-compose

      # Confirm podman is working
      podman --version

ssh:
  localPort: 60022

portForwards:
  - guestPort: 8080
    hostPort: 8080
  - guestPort: 5555
    hostPort: 5555

env:
  DOCKER_HOST: "unix:///run/user/1000/podman/podman.sock"
